### ISSUE TITLE
Custom error presentation logic messes with the behaviour of my code

### ISSUE THREAD

**Issue by Avaq** [bearror/oletus#4]
I'm opening this issue to discuss a matter that doesn't have a straight-forward enough solution for a PR.

My code uses the `.stack` property in Error instances. Overriding `Error.prepareStackTrace` before running a test, as done in the snippet below, means that while I'm testing this functionality, my code behaves differently from how it should.

https://github.com/bearror/oletus/blob/ad56f38dbe810e067ad4860f35e12927c5b24cbe/oletus.mjs#L4

I have attempted to fix this issue without success, by moving the location where `prepareStackTrace` is overridden closer to where `.stack` is accessed by Oletus:

https://github.com/Avaq/oletus/blob/309e79c0e19b2a949aedc4d26aeb89fc8f19744d/oletus.mjs#L18-L21

Yet I realize that even if I were successful, there is another issue with Oletus' approach to formatting errors, and that is that it assumes that all assertions are made directly at the testing location, and thus that only the first stack trace entry is relevant to the user.

For me, this is not the case. I have abstracted over assertions, and therefore Oletus shows me the same location for every failing assertion. It might therefore be worth considering the removal of the custom error formatting logic altogether, and just presenting the user with the default `e.stack` as a message.

If you do just present `e.stack`, then a user can always modify the output from that by overriding `Error.prepareStackTrace` themselves.

**Comment by bearror** [comment]
When I was initially writing this, I wanted to have the kind of nice error formatting more fully-fledged runners such as AVA give. I do see that overriding `prepareStackTrace` is definitely wrong, and the formatting isn't worth the trouble it causes.

I'd say that going with `e.stack` as you suggested is the way to go. It'll be more future-proof as well.

If you already have a PR in the works, feel free to post it. Otherwise -- this being an issue where Oletus is clearly wrong -- I don't mind fixing it myself.

**Comment by Avaq** [comment]
I may have found a solution to the problem, and while I'd still like to see the whole stack trace, this means the `location` can be preserved. I'll happily submit a PR.

**Comment by bearror** [comment]
I'd love to see it!

The goal here was/is to have the `location` (or stack) information visually distinguishable from the `message`. When experimenting with this locally, the error reporting suffers when just setting `message = e.stack`.

IMO the optimal solution would be if just the actual stack could be extracted somehow -- and be used instead of `location`.

**Comment by Avaq** [comment]
My idea, which was to capture the raw Callsites as a side-effect of `preareStackTrace`, doesn't work because the built-in `Error.prepareStackTrace` is `undefined` (not callable though user code). I'm exploring other options.

**Comment by bearror** [comment]
To illustrate, here's a test I intentionally broke. First with `e.stack` and then the current parsed messaging. In simple cases such as these the additional lines are unhelpful.
```
✖ single token                            

AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  [
    {
+     data: '#Hello, World!',
-     data: '#Helo, World!',
      type: [
...
    }
  ]
    at _129‍.r.t (/Users/joonatanvuorinen/Github/flat-text-sequencer/test/test-markdown.js:16:5)
    at test (/Users/joonatanvuorinen/Github/oletus/oletus.mjs:8:11)
    at Object.<anonymous> (/Users/joonatanvuorinen/Github/flat-text-sequencer/test/test-markdown.js:13:1)
    at C (/Users/joonatanvuorinen/Github/flat-text-sequencer/node_modules/esm/esm.js:1:179076)
    at Object.run (/Users/joonatanvuorinen/Github/flat-text-sequencer/node_modules/esm/esm.js:1:178697)
    at Object.<anonymous> (/Users/joonatanvuorinen/Github/flat-text-sequencer/test/test-markdown.js:1:86)
    at Module.e (/Users/joonatanvuorinen/Github/flat-text-sequencer/node_modules/esm/esm.js:1:11683)
    at X (/Users/joonatanvuorinen/Github/flat-text-sequencer/node_modules/esm/esm.js:1:199486)
    at /Users/joonatanvuorinen/Github/flat-text-sequencer/node_modules/esm/esm.js:1:201071
    at module.exports.r.a (/Users/joonatanvuorinen/Github/flat-text-sequencer/node_modules/esm/esm.js:1:201305)
```

versus

```
✖ single token                            
test-markdown.js:16
  [
    {
+     data: '#Hello, World!',
-     data: '#Helo, World!',
      type: [
...
    }
  ]
```

**Comment by Avaq** [comment]
I have suggested an approach in #5 that tries to find a middle-ground between your requirements and mine.
